export const DIALOG_TYPES = {
  DIALOG_OPEN: 'DIALOG_OPEN',
}
export const FILTER_TYPES = {
  FILTER_LIST: 'FILTER_LIST',
  SKU_SELECT: 'SKU_SELECT',
  ASIN_SELECT: 'ASIN_SELECT',
  FULFIL_SELECT: 'FULFIL_SELECT'
}

export const MARKETPLACE_TYPES = {
  MARKETPLACE_SELECT: 'MARKETPLACE_SELECT',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_SP_DATA: 'GET_SP_DATA',
  GET_IMPORT_DATA: 'GET_IMPORT_DATA',
  GET_IMPORT_DATA_NAME: 'GET_IMPORT_DATA_NAME'
}

export const ROUTER_SELECTED_TYPES = {
  ROUTER_SELECTED_TITLE: 'ROUTER_SELECTED_TITLE'
}

export const PRICE_UPDATE_REQ_STATUS = {
  PRICE_UPDATE_REQ_STATUS: 'PRICE_UPDATE_REQ_STATUS'
}

export const NOTIFICATION_TYPES = {
  NOTIFICATION_TYPES: 'NOTIFICATION_TYPES'
}